### ISSUE TITLE
Improve the implementation of table-arrows class.

### ISSUE THREAD

**Issue by LeeWannacott** [LeeWannacott/table-sort-js#14]
table-arrows class displays desc and aesc arrows on sort. However it's implementation is mediocre, another-words it doesn't look that great.

**Comment by horrificCoder** [comment]
@LeeWannacott Can I work on this?

**Comment by LeeWannacott** [comment]
> @LeeWannacott Can I work on this?

Sure! I was thinking smaller icons and maybe a neutral icon before they click or something : 🤔 maybe look at other table sorting libraries like datatables for inspiration. Could also maybe do custom icons from the user.

**Comment by omkarpatole1799** [comment]
I wanted to ask that can I work on this, if there are no assignee to this issue.

**Comment by LeeWannacott** [comment]
@omkarpatole1799 Sure, I don't think @horrificCoder is working on it.

**Comment by omkarpatole1799** [comment]
Ok I'll start working on it from today evening.
But can you just elaborate what exactly is your need in some details.

**Comment by omkarpatole1799** [comment]
Hey, @LeeWannacott I have started working on the above issue #14.
I have installed all the packages, when I start the project I'm getting the below error cause you tell me what might be wrong. 



`Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Ujjwala Patole\Desktop\table-sort-js\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`
